---
name: Linting

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-python@v5.1.0
      - uses: pre-commit/action@v3.0.1
