---
name: Linting

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - name: Run yamllint
        uses: frenck/action-yamllint@v1
